FROM ubuntu:20.04
ARG TARGETARCH
LABEL maintainer="Hafizhuddin Amin"

WORKDIR /var/www/html

ENV DEBIAN_FRONTEND noninteractive
ENV TZ=Asia/Jakarta

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
COPY "instantclient/${TARGETARCH}" /opt/oracle/instantclient

RUN ln -s /opt/oracle/instantclient/libclntsh.so.12.1 /opt/oracle/instantclient/libclntsh.so \
    && ln -s /opt/oracle/instantclient/libclntshcore.so.12.1 /opt/oracle/instantclient/libclntshcore.so \
    && ln -s /opt/oracle/instantclient/libocci.so.12.1 /opt/oracle/instantclient/libocci.so \
    && apt-get update \
    && apt-get install -y gnupg curl ca-certificates zip unzip libterm-readline-perl-perl \
    && mkdir -p ~/.gnupg \
    && chmod 600 ~/.gnupg \
    && echo "disable-ipv6" >> ~/.gnupg/dirmngr.conf \
    && apt-key adv --homedir ~/.gnupg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys E5267A6C \
    && apt-key adv --homedir ~/.gnupg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C300EE8C \
    && echo "deb http://ppa.launchpad.net/ondrej/php/ubuntu focal main" > /etc/apt/sources.list.d/ppa_ondrej_php.list \
    && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update \
    && ACCEPT_EULA=Y apt-get install -y msodbcsql18 unixodbc-dev php7.4-common php7.4-dev php7.4-cli php7.4-zip php7.4-curl php7.4-xml php7.4-fpm net-tools php7.4-cli \
        php7.4-gd php7.4-curl php7.4-redis php7.4-mbstring php7.4-xml php7.4-zip php7.4-bcmath php7.4-opcache php7.4-xdebug php7.4-excimer php7.4-xhprof graphviz \
        php7.4-intl php7.4-msgpack php7.4-igbinary php7.4-ldap php7.4-mysql libaio1 \
    && echo 'instantclient,/opt/oracle/instantclient' |  pecl install oci8-2.2.0 \
    && pecl install sqlsrv-5.8.1 \
    && pecl install pdo_sqlsrv-5.8.1 \
    && rm -rf /opt/oracle/instantclient/sdk \
    && apt-get -y remove php-pear php7.4-dev unixodbc-dev \
    && apt-get -y autoremove \
    && apt-get clean \
    && rm -rf /var/lib/apt/* /tmp/* /var/cache/apt/* /var/tmp/* /usr/include
    
COPY php.ini /etc/php/7.4/cli/conf.d/99-app.ini
COPY php.ini /etc/php/7.4/fpm/conf.d/99-app.ini
COPY php-fpm.conf /etc/php/7.4/fpm/pool.d/www.conf
RUN echo '/opt/oracle/instantclient' > /etc/ld.so.conf.d/oracle.conf && ldconfig
RUN php -r "readfile('http://getcomposer.org/installer');" | php -- --install-dir=/usr/bin/ --filename=composer 

EXPOSE 9000
WORKDIR /var/www/html
CMD ["php-fpm7.4", "--nodaemonize"]
